
## План анализа

В ходе EDA будут выполнены следующие шаги:

1. Загрузка и первичный осмотр данных  
2. Анализ пропусков и типов данных 
3. Поиск выбросов и аномалий  
4. Анализ целевой переменной  
5. Исследование числовых признаков  
6. Анализ корреляций  
7. Анализ категориальных признаков

Импорт нужных библиотек

In [134]:
import pandas as pd
import numpy as np
import plotly.express as px

Загрузка данных

Было решено дополнительно дублировать датасет, который будет очищаться для дальнейших этапов анализа, где это необходимо. А также для последующего выявдения важных признаков уже на очищенном датасете

In [135]:
df_train = pd.read_csv('../data/EDA_data/train_EDA', index_col='id')
df_cleaned = df_train.copy()

Выведим первые 5 записей

In [136]:
df_train.head(5)

,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,...,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc,time_block
id,,,,,,,,,,,,,,,,,,,,,
1,2011-08-20,43,27.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,4,0,13,22,1,0,52,4,5850000,B1
2,2011-08-23,34,19.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,3,0,15,29,1,10,66,14,6000000,B1
3,2011-08-27,43,29.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,3,0,11,27,0,4,67,10,5700000,B1
4,2011-09-01,89,50.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,1,4,4,0,0,26,3,13100000,B1
5,2011-09-05,77,77.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,108,17,135,236,2,91,195,14,16331452,B1

In [137]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25445 entries, 1 to 25447
Columns: 292 entries, timestamp to time_block
dtypes: float64(119), int64(156), object(17)
memory usage: 56.9+ MB

Большая часть признаков числовые, посмотрим есть ли дубликаты наблюдений

In [138]:
print(df_train.duplicated().sum())
df_train[df_train.duplicated()]

7

,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,...,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc,time_block
id,,,,,,,,,,,,,,,,,,,,,
3362,2012-08-27,59,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,3,15,1,0,24,4,4506800,B1
4331,2012-10-22,61,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,1,5,4,0,1,32,5,8248500,B1
6994,2013-04-03,42,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,2,16,1,0,20,4,3444000,B2
8062,2013-05-22,68,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,2,16,1,0,20,4,5406690,B2
8656,2013-06-24,40,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,4,6,0,0,4,1,4112800,B2
14007,2014-01-22,46,28.0,1.0,9.0,1.0,1968.0,2.0,5.0,NaN,...,1,0,13,15,1,1,61,4,3000000,B3
17407,2014-04-15,134,134.0,1.0,1.0,1.0,0.0,3.0,0.0,1.0,...,0,0,0,1,0,0,0,0,5798496,B4

Удалим дубликаты и переведем timestamp в datetime формат

In [139]:
df_cleaned['timestamp'] = pd.to_datetime(df_cleaned['timestamp'])
print(min(df_cleaned['timestamp']), max(df_cleaned['timestamp']))

2011-08-20 00:00:00 2014-11-27 00:00:00

In [140]:
df_cleaned = df_cleaned.drop_duplicates()

Посмотрим есть ли в данных аномалии в виде нулей и отрицательных значений признаков, а также выведем небольшую сводку статистик по ним

In [141]:
numeric_columns = df_train.select_dtypes(include=[np.number]).columns.tolist()

zero_negative_summary = []

for col in numeric_columns:
    zero_count = (df_train[col] == 0).sum()
    neg_count = (df_train[col] < 0).sum()

    zero_negative_summary.append({
        "column": col,
        "zero_count": zero_count,
        "zero_share": zero_count / len(df_train),
        "negative_count": neg_count,
        "negative_share": neg_count / len(df_train),
        "min": df_train[col].min(),
        "median": df_train[col].median(),
        "max": df_train[col].max()
    })

zero_negative_summary = pd.DataFrame(zero_negative_summary).sort_values("zero_count", ascending=False)
zero_negative_summary

,column,zero_count,zero_share,negative_count,negative_share,min,median,max
155,mosque_count_500,25314,0.994852,0,0.0,0.00,0.00,1.000000e+00
178,mosque_count_1000,24938,0.980075,0,0.0,0.00,0.00,1.000000e+00
152,cafe_count_500_price_high,24810,0.975044,0,0.0,0.00,0.00,3.000000e+00
201,mosque_count_1500,24443,0.960621,0,0.0,0.00,0.00,1.000000e+00
175,cafe_count_1000_price_high,24367,0.957634,0,0.0,0.00,0.00,7.000000e+00
...,...,...,...,...,...,...,...,...
28,full_all,0,0.000000,0,0.0,2546.00,85721.00,1.716730e+06
252,prom_part_5000,0,0.000000,0,0.0,0.21,8.75,2.856000e+01
251,green_part_5000,0,0.000000,0,0.0,3.52,19.63,7.229000e+01
32,young_male,0,0.000000,0,0.0,189.00,5470.00,2.097700e+04
274,price_doc,0,0.000000,0,0.0,100000.00,6136900.00,1.111111e+08

Отрицательных значений нет, а большинство нулей кажутся валидными в виде особенностей самих признаков

In [142]:
zero_negative_summary.describe()

,zero_count,zero_share,negative_count,negative_share,min,median,max
count,275.000000,275.000000,275.0,275.0,2.750000e+02,2.750000e+02,2.750000e+02
mean,5259.730909,0.206710,0.0,0.0,8.022663e+03,6.988129e+04,1.399317e+06
std,7559.879831,0.297107,0.0,0.0,1.256443e+05,7.258072e+05,1.416086e+07
min,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,5.218671e-01
25%,0.000000,0.000000,0.0,0.0,0.000000e+00,1.000000e+00,3.350000e+01
50%,516.000000,0.020279,0.0,0.0,0.000000e+00,5.000000e+00,9.088892e+01
75%,8500.000000,0.334054,0.0,0.0,2.919749e-01,6.750000e+01,1.854165e+03
max,25314.000000,0.994852,0.0,0.0,2.081628e+06,1.032047e+07,2.060718e+08

Отдельно рассмотрим основные признаки, характеризующие недвижимость

In [143]:
zero_negative_summary[zero_negative_summary['column'].isin(['price_doc', 'full_sq', 'life_sq', 'floor', 'max_floor', 'build_year', 'num_room', 'kitch_sq', 'state', 'raion_popul'])]

,column,zero_count,zero_share,negative_count,negative_share,min,median,max
7,kitch_sq,1050,0.041265,0,0.0,0.0,6.0,2014.0
3,max_floor,407,0.015995,0,0.0,0.0,12.0,99.0
5,build_year,313,0.012301,0,0.0,0.0,1979.0,20052009.0
1,life_sq,39,0.001533,0,0.0,0.0,30.0,7478.0
6,num_room,13,0.000511,0,0.0,0.0,2.0,19.0
2,floor,9,0.000354,0,0.0,0.0,7.0,77.0
0,full_sq,2,0.000079,0,0.0,0.0,48.0,5326.0
8,state,0,0.000000,0,0.0,1.0,2.0,33.0
10,raion_popul,0,0.000000,0,0.0,2546.0,83844.0,247469.0
274,price_doc,0,0.000000,0,0.0,100000.0,6136900.0,111111112.0

Здесь явно есть аномалии в виде нулей, а также крайне больших значений

In [144]:
for i in ['price_doc', 'full_sq', 'life_sq', 'floor', 'max_floor', 'build_year', 'num_room', 'state', 'raion_popul']:
    df_cleaned.loc[df_cleaned[i] == 0, i] = np.nan

df_cleaned.loc[df_cleaned['max_floor'] < df_cleaned['floor'], ['max_floor', 'floor']] = np.nan
df_cleaned.loc[df_cleaned['life_sq'] > df_cleaned['full_sq'], ['life_sq', 'full_sq']] = np.nan
df_cleaned.loc[df_cleaned['kitch_sq'] > df_cleaned['full_sq'], ['kitch_sq', 'full_sq']] = np.nan
df_cleaned.loc[df_cleaned['kitch_sq'] > df_cleaned['life_sq'], ['kitch_sq', 'life_sq']] = np.nan
df_cleaned.loc[df_cleaned['kitch_sq'] > df_cleaned['life_sq'], ['kitch_sq', 'life_sq']] = np.nan
df_cleaned.loc[(df_cleaned['build_year'] > 2015) | (df_cleaned['build_year'] < 1800), ['build_year']] = np.nan

Устранение аномалий выше следует добавить и в дальнейшую предобработку данных

До удаления явных аномалий посмотрим на ассиметрию в числовых признаках

In [145]:
skew_features = df_train.select_dtypes(include='number').skew().sort_values(ascending=False)
skew_features.head(10)

life_sq                              114.760284
build_year                           113.533141
full_sq                               88.288128
kitch_sq                              67.143328
mosque_count_500                      13.829836
public_transport_station_min_walk     10.468754
public_transport_station_km           10.468754
leisure_count_500                     10.393785
build_count_foam                       8.914392
cafe_count_1000_price_high             8.680096
dtype: float64

А теперь после

In [146]:
skew_features = df_cleaned.select_dtypes(include='number').skew().sort_values(ascending=False)
skew_features.head(10)

full_sq                              88.321061
mosque_count_500                     13.827904
public_transport_station_min_walk    10.471238
public_transport_station_km          10.471238
leisure_count_500                    10.392348
build_count_foam                      8.913750
cafe_count_1000_price_high            8.678869
kindergarten_km                       8.314883
preschool_km                          7.973744
school_km                             7.957033
dtype: float64

Остается крайне большой показатель общей площади, посмотрим какие значения он принимает и отсортируем

In [147]:
df_train['full_sq'].value_counts().sort_index()

full_sq
0        2
1       16
5        1
6        1
9        1
        ..
603      1
634      2
637      1
729      1
5326     1
Name: count, Length: 207, dtype: int64

Есть также явные аномалии в виде очень большого и нескольких очень маленьких значений данного признака, для лучшего последующего анализа удалим их тоже

In [148]:
df_train.loc[(df_train['full_sq'] > 1000) | (df_train['full_sq'] < 10)]

,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,...,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc,time_block
id,,,,,,,,,,,,,,,,,,,,,
1189,2012-02-14,9,44.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,3,0,9,18,0,10,53,9,6300000,B1
2012,2012-04-25,5,40.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,10,14,0,2,50,5,5770000,B1
3530,2012-09-07,5326,22.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,5,16,0,2,43,6,6868818,B1
6115,2013-02-22,6,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,7,1,0,12,1,5177040,B2
11335,2013-10-18,1,40.0,10.0,17.0,1.0,2013.0,1.0,1.0,1.0,...,0,0,1,5,1,0,14,1,3357774,B3
16292,2014-03-20,1,1.0,1.0,1.0,4.0,1.0,1.0,1.0,3.0,...,0,0,1,7,1,0,12,1,4457400,B4
16741,2014-03-31,1,1.0,1.0,1.0,4.0,1.0,1.0,1.0,3.0,...,0,0,1,7,1,0,12,1,7820575,B4
17197,2014-04-09,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,4,1,11,14,0,1,72,9,13066000,B4
17935,2014-04-28,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0,0,1,7,1,0,12,1,4425000,B4
18603,2014-05-19,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,...,141,26,150,249,2,105,203,13,6675730,B4
22174,2014-09-03,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,0,2,12,0,1,10,0,6256186,B5
22415,2014-09-11,1,47.0,11.0,17.0,1.0,2014.0,1.0,1.0,1.0,...,118,24,68,120,0,73,167,9,14923206,B5
22725,2014-09-20,1,1.0,1.0,25.0,1.0,2014.0,1.0,1.0,1.0,...,0,0,4,6,0,0,5,1,4740000,B5
22798,2014-09-23,1,1.0,7.0,19.0,1.0,2015.0,3.0,1.0,1.0,...,0,0,1,6,0,0,6,1,5591788,B5
22874,2014-09-24,1,1.0,1.0,1.0,1.0,2015.0,1.0,1.0,1.0,...,0,0,4,6,0,0,5,1,4740000,B5
23051,2014-09-29,1,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,...,15,1,11,25,0,6,97,4,27259184,B5
23231,2014-10-03,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,3,0,15,28,0,8,67,15,13452318,B5
23576,2014-10-15,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,7,2,20,38,1,12,79,12,11731927,B5
23729,2014-10-20,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0,0,4,6,0,0,5,1,4819000,B5
24299,2014-11-05,0,77.0,4.0,17.0,1.0,0.0,3.0,0.0,1.0,...,1,0,2,12,0,1,10,0,8167508,B5
24630,2014-11-12,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0,0,1,7,1,0,12,1,5000550,B5
24895,2014-11-18,1,1.0,26.0,1.0,1.0,1.0,1.0,1.0,1.0,...,3,0,12,10,0,1,49,5,17035200,B5

Более того в данных подтверждается, что такие наблюдения являются аномалиями из за несоответсвия в цене

In [149]:
df_cleaned.loc[(df_train['full_sq'] > 1000) | (df_cleaned['full_sq'] < 10), ['full_sq']] = np.nan

In [150]:
skew_features = df_cleaned.select_dtypes(include='number').skew().sort_values(ascending=False)
skew_features

mosque_count_500                     13.827904
public_transport_station_min_walk    10.471238
public_transport_station_km          10.471238
leisure_count_500                    10.392348
build_count_foam                      8.913750
                                       ...
ID_big_road2                          0.303432
ekder_all                             0.224901
ekder_female                          0.212069
ID_bus_terminal                       0.175107
build_year                           -0.054155
Length: 275, dtype: float64

In [151]:
skew_features.describe()

count    275.000000
mean       3.235835
std        2.239827
min       -0.054155
25%        1.212628
50%        2.917077
75%        4.889737
max       13.827904
dtype: float64

Теперь числовые данные в большинстве своем распределенны не так ассиметрично

#### Рассмотрим нули и пропуски в данных на графиках

In [152]:
zero_negative_summary_30 = zero_negative_summary.head(30)
fig = px.bar(x=zero_negative_summary_30['zero_count'],
            y=zero_negative_summary_30['column'],
            title='Количество нулей по признакам, топ 30',
            )
fig.update_layout(
    xaxis_title="Кол во нулей",
    yaxis_title="Числовые признаки"
)
fig.show()

In [153]:
df_na_sum = df_train.isna().sum().reset_index().rename(columns={0:'NA_sum', 'index':'feature'}).sort_values('NA_sum', ascending=False).head(40)
fig = px.bar(x=df_na_sum['NA_sum'], y=df_na_sum['feature'], title='Количество пропусков по признакам, топ 40')
fig.update_layout(
    xaxis_title="Кол во пропусков",
    yaxis_title="Числовые признаки"
)
fig.show()

## Анализ таргета

In [154]:
print(f'Кол во пропусков у таргета {df_train['price_doc'].isna().sum()}')
print(f"Кол во нулей у таргета {(df_train['price_doc']==0).sum()}")

Кол во пропусков у таргета 0
Кол во нулей у таргета 0

In [155]:
df_train['price_doc'].describe()

count    2.544500e+04
mean     6.945362e+06
std      4.615799e+06
min      1.000000e+05
25%      4.640000e+06
50%      6.136900e+06
75%      8.050000e+06
max      1.111111e+08
Name: price_doc, dtype: float64

In [156]:
fig = px.histogram(x=df_train['price_doc'], marginal='box')
fig.update_layout(
    title='Распределение цены',
    xaxis_title="Цена",
    yaxis_title="Кол во"
)
fig.show()

У таргета есть явный тяжелый правый хвост, попробуем логарифмировать

In [157]:
fig = px.histogram(x=np.log(df_train['price_doc']), marginal='box')
fig.update_layout(
    title='Распределение логарифмированной цены',
    xaxis_title="Логарифм цены",
    yaxis_title="Кол во"
)
fig.show()

Логарифмирование улучшает ситуацию, как вариант будет рассмотреть оба таргета при моделировании

### Динамика таргета

In [158]:
group_by_month = df_cleaned.groupby(df_cleaned['timestamp'].dt.to_period('M'))['price_doc'].agg(['mean', 'median']).reset_index().sort_values('timestamp')
group_by_month['timestamp'] = group_by_month['timestamp'].dt.to_timestamp()
group_by_month

    timestamp          mean     median
0  2011-08-01  5.850000e+06  5850000.0
1  2011-09-01  6.007330e+06  5200000.0
2  2011-10-01  5.808422e+06  5500000.0
3  2011-11-01  6.115835e+06  5600000.0
4  2011-12-01  5.824306e+06  5450000.0
5  2012-01-01  6.884006e+06  6100000.0
6  2012-02-01  6.807456e+06  5700000.0
7  2012-03-01  6.765834e+06  6175000.0
8  2012-04-01  6.800689e+06  6200000.0
9  2012-05-01  7.226219e+06  6100000.0
10 2012-06-01  7.134101e+06  6330000.0
11 2012-07-01  6.311195e+06  5800000.0
12 2012-08-01  6.168567e+06  5650000.0
13 2012-09-01  6.401642e+06  5600000.0
14 2012-10-01  5.760664e+06  5150411.5
15 2012-11-01  5.749250e+06  5140640.0
16 2012-12-01  5.552361e+06  4975100.0
17 2013-01-01  6.394840e+06  5409889.0
18 2013-02-01  6.238732e+06  5649280.0
19 2013-03-01  6.598500e+06  5754800.0
20 2013-04-01  6.486943e+06  5653850.5
21 2013-05-01  6.085622e+06  5500000.0
22 2013-06-01  6.669491e+06  5900000.0
23 2013-07-01  6.851887e+06  5930866.0
24 2013-08-01  6.741660e+06  5897600.0
25 2013-09-01  6.910704e+06  6000000.0
26 2013-10-01  6.801979e+06  6150000.0
27 2013-11-01  6.833484e+06  6100000.0
28 2013-12-01  7.164638e+06  6325884.0
29 2014-01-01  7.006642e+06  6272000.0
30 2014-02-01  7.068843e+06  6389080.0
31 2014-03-01  7.340741e+06  6400000.0
32 2014-04-01  7.660892e+06  6680000.0
33 2014-05-01  7.643710e+06  6600000.0
34 2014-06-01  7.144800e+06  6481389.5
35 2014-07-01  7.318232e+06  6500000.0
36 2014-08-01  7.723494e+06  6671450.0
37 2014-09-01  7.849181e+06  6900000.0
38 2014-10-01  7.312297e+06  6550000.0
39 2014-11-01  7.385674e+06  6581700.0

Также построим линейный график для наглядности

In [159]:
fig = px.line(
    group_by_month,
    x='timestamp',
    y=['mean', 'median']
)

fig.update_layout(
    title='Динамика средней и медианной цены',
    xaxis_title="Месяц",
    yaxis_title="Цена"
)

fig.show()

В общем значение таргета имеет восходящий тренд кроме падения в начале 2013 года, что объясняется экономической ситуацией на тот момент

In [160]:
group_by_month['median'].autocorr(lag=1)

np.float64(0.8432638074104994)

In [161]:
group_by_month['median_diff'] = group_by_month['median'].pct_change()*100
group_by_month['median_diff'].autocorr(lag=1)

np.float64(-0.3246670422747988)

Также были проанализированы лаги:
- сильная положительная корреляция текущего месяца с предыдущим
- а вот с измененим уже не все так явно, поэтому данный показатель лучше не рассматривать

#### Анализ выбросов

In [162]:
num_features = df_train.select_dtypes(include='number').columns.to_list()

outliers = {}

for i in num_features:
    q1 = df_train[i].quantile(0.25)
    q3 = df_train[i].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    left_outliers = (df_train[i] < lower_bound).sum()
    right_outliers = (df_train[i] > upper_bound).sum()

    outliers[i] = {
        "left_outliers": left_outliers,
        "right_outliers": right_outliers,
        "total_outliers": left_outliers + right_outliers
    }

df_outliers = pd.DataFrame.from_dict(outliers, orient='index')
df_outliers.sort_values('total_outliers', ascending=False).head(20)

                            left_outliers  right_outliers  total_outliers
church_count_500                        0            6045            6045
trc_sqm_500                             0            5978            5978
office_count_500                        0            5615            5615
office_sqm_500                          0            5526            5526
cafe_count_1500_price_4000              0            5335            5335
build_count_frame                       0            4638            4638
mosque_count_3000                       0            4605            4605
build_count_wood                        0            4506            4506
cafe_count_500_price_2500               0            4377            4377
build_count_mix                         0            4204            4204
school_km                               0            4140            4140
leisure_count_1000                      0            4061            4061
preschool_km                            0            3753            3753
build_count_before_1920                 0            3742            3742
build_count_slag                        0            3665            3665
cafe_count_3000_price_high              0            3606            3606
cafe_count_500_na_price                 0            3514            3514
cafe_count_3000_price_2500              0            3492            3492
office_sqm_2000                         0            3355            3355
cafe_count_5000_price_4000              0            3340            3340

Кажется что в основном выбросы наблюдаются только в признаках, характеризующих местность расположения недвижимостии и несут только левостороннюю ассиметрию, возьмем для примера church_count_500, чтобы показать, что подобное не является аномалией

In [163]:
df_train[df_train['church_count_500']==df_train['church_count_500'].max()]['sub_area']

id
15369    Tverskoe
Name: sub_area, dtype: object

Так например недвижимость с наибольшим кол вом церквей в радиусе 500 м находится на Тверской, что кажется довольно реальным наблюдением

### Корреляционный анализ

In [164]:
corr_matrix = df_cleaned.corr(numeric_only=True)

corr_pairs = (
    corr_matrix
    .unstack()
    .reset_index()
)

corr_pairs.columns = ['feature_1', 'feature_2', 'correlation']

corr_pairs = corr_pairs[
    corr_pairs['feature_1'] != corr_pairs['feature_2']
]


corr_pairs = corr_pairs[
    corr_pairs['correlation'].abs() >= 0.7
]
corr_pairs['pair'] = corr_pairs.apply(
    lambda x: tuple(sorted([x['feature_1'], x['feature_2']])),
    axis=1
)

corr_pairs = corr_pairs.drop_duplicates('pair')

corr_pairs = corr_pairs.sort_values(
    by='correlation',
    ascending=False
)

corr_pairs[['feature_1', 'feature_2', 'correlation']]

,feature_1,feature_2,correlation
23185,railroad_station_walk_km,railroad_station_walk_min,1.000000
24841,public_transport_station_km,public_transport_station_min_walk,1.000000
4443,children_school,7_14_all,1.000000
3615,children_preschool,0_6_all,1.000000
20425,metro_min_walk,metro_km_walk,1.000000
...,...,...,...
26930,kremlin_km,trc_count_5000,-0.799596
28597,zd_vokzaly_avto_km,sport_count_5000,-0.813105
26397,sadovoe_km,sport_count_5000,-0.814490
26672,bulvar_ring_km,sport_count_5000,-0.828969
26947,kremlin_km,sport_count_5000,-0.832858

В данных присутствует довольно сильная мультиколлинеарность, а некоторые признаки и вовсе имеюют значение корреляции равное 1.
Этот факт стоит учесть при дальнейшем отборе признаков!

In [165]:
corr_pairs[corr_pairs['correlation']>=0.99][['feature_1', 'feature_2', 'correlation']]

,feature_1,feature_2,correlation
23185,railroad_station_walk_km,railroad_station_walk_min,1.000000
24841,public_transport_station_km,public_transport_station_min_walk,1.000000
4443,children_school,7_14_all,1.000000
3615,children_preschool,0_6_all,1.000000
20425,metro_min_walk,metro_km_walk,1.000000
...,...,...,...
69838,office_count_5000,cafe_count_5000_price_1000,0.990488
64588,cafe_count_3000,cafe_count_3000_na_price,0.990437
59618,cafe_count_2000_price_500,cafe_count_2000_price_1500,0.990390
72315,cafe_count_5000_price_500,cafe_count_5000_price_2500,0.990292
73141,cafe_count_5000_price_2500,cafe_count_5000_price_4000,0.990106

Стоит также заметить что большинство сильно коррелирующих признаков несут почти одинаковую информацию

Отдельно рассмотрим корреляцию с таргетом

In [166]:
target_corr = (
    corr_matrix['price_doc']
    .sort_values(ascending=False)
)

target_corr

price_doc             1.000000
full_sq               0.552180
num_room              0.474121
life_sq               0.443700
sport_count_3000      0.292215
                        ...
ttk_km               -0.264138
bulvar_ring_km       -0.271789
kremlin_km           -0.272156
sadovoe_km           -0.275756
zd_vokzaly_avto_km   -0.278061
Name: price_doc, Length: 275, dtype: float64

Тут точно можно выделить кол во комнат(num_room) и общую площадь(full_sq) как наиболее значимые признаки

### Анализ категориальных признаков

In [167]:
cat_features = df_train.select_dtypes(include='object').columns

nuni = []

for i in cat_features:
    nuni.append(df_train[i].nunique())

cat_df = pd.DataFrame({
    'feature': cat_features,
    'nunique': nuni
})

cat_df

                      feature  nunique
0                   timestamp      986
1                product_type        2
2                    sub_area      146
3      culture_objects_top_25        2
4   thermal_power_plant_raion        2
5          incineration_raion        2
6         oil_chemistry_raion        2
7             radiation_raion        2
8     railroad_terminal_raion        2
9            big_market_raion        2
10      nuclear_reactor_raion        2
11   detention_facility_raion        2
12                water_1line        2
13            big_road1_1line        2
14             railroad_1line        2
15                    ecology        5
16                 time_block        5

In [168]:
df_train[cat_features]

,timestamp,product_type,sub_area,culture_objects_top_25,thermal_power_plant_raion,incineration_raion,oil_chemistry_raion,radiation_raion,railroad_terminal_raion,big_market_raion,nuclear_reactor_raion,detention_facility_raion,water_1line,big_road1_1line,railroad_1line,ecology,time_block
id,,,,,,,,,,,,,,,,,
1,2011-08-20,Investment,Bibirevo,no,no,no,no,no,no,no,no,no,no,no,no,good,B1
2,2011-08-23,Investment,Nagatinskij Zaton,yes,no,no,no,no,no,no,no,no,no,no,no,excellent,B1
3,2011-08-27,Investment,Tekstil'shhiki,no,no,no,no,yes,no,no,no,no,no,no,no,poor,B1
4,2011-09-01,Investment,Mitino,no,no,no,no,no,no,no,no,no,no,no,no,good,B1
5,2011-09-05,Investment,Basmannoe,no,no,no,no,yes,yes,no,no,no,no,no,yes,excellent,B1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25443,2014-11-27,Investment,Nagatinskij Zaton,yes,no,no,no,no,no,no,no,no,no,no,no,excellent,B5
25444,2014-11-27,Investment,Bogorodskoe,no,no,no,no,yes,no,no,no,no,no,no,no,excellent,B5
25445,2014-11-27,OwnerOccupier,Poselenie Novofedorovskoe,no,no,no,no,no,no,no,no,no,yes,no,no,no data,B5
25446,2014-11-27,Investment,Kuncevo,no,no,no,no,yes,no,no,no,no,no,no,no,satisfactory,B5
25447,2014-11-27,Investment,Ljublino,no,no,no,no,yes,no,yes,no,yes,no,no,no,excellent,B5

In [169]:
df_train['sub_area'].value_counts()

sub_area
Nekrasovka                        1503
Poselenie Sosenskoe               1437
Poselenie Vnukovskoe               934
Poselenie Moskovskij               749
Poselenie Voskresenskoe            677
                                  ...
Poselenie Shhapovskoe                2
Molzhaninovskoe                      2
Poselenie Klenovskoe                 1
Poselenie Kievskij                   1
Poselenie Mihajlovo-Jarcevskoe       1
Name: count, Length: 146, dtype: int64

Кажется что ошибок в названиях нет, разве что некоторые значения встречаются очень редко

Посмотрим на баланс классов и как отдельные категории признаков влияют на таргет

In [170]:
df_train['product_type'].value_counts()

product_type
Investment       16576
OwnerOccupier     8869
Name: count, dtype: int64

In [171]:
df_train['ecology'].value_counts()

ecology
poor            6786
good            6270
no data         6104
excellent       3202
satisfactory    3083
Name: count, dtype: int64

Рассмотрим бокс плоты как с обычной ценой так и с логарифмированной

In [172]:
fig = px.box(x=df_train['ecology'], y=df_train['price_doc'])
fig.update_layout(
    title='Зависит ли цена от экологии района?',
    xaxis_title="",
    yaxis_title="Цена"
)
fig.show()

In [173]:
fig = px.box(x=df_train['ecology'], y=np.log(df_train['price_doc']))
fig.update_layout(
    title='Зависит ли цена от экологии района? (логарифм)',
    xaxis_title="",
    yaxis_title="Логарифм цены"
)
fig.show()

Нельзя точно сказать какую важную роль влияет экология при оценке недвижимости, но можно заметить что наблюдения у которых данные отсутсвуют имеют значения цены ниже

In [174]:
fig = px.box(x=df_train['product_type'], y=df_train['price_doc'])
fig.update_layout(
    title='Какой тип недвижимости продается дороже?',
    xaxis_title="",
    yaxis_title="Цена"
)
fig.show()

In [175]:
fig = px.box(x=df_train['product_type'], y=np.log(df_train['price_doc']))
fig.update_layout(
    title='Какой тип недвижимости продается дороже? (логарифм)',
    xaxis_title="",
    yaxis_title="Логарифм цены"
)
fig.show()

Видно, что как правильно коммерческая недвижимость дороже купленной для собственного проживания

In [176]:
yes_no_features = cat_features.drop(['ecology', 'product_type', 'sub_area', 'timestamp'])
df_train[yes_no_features]
summary_df = pd.DataFrame({
    'feature': yes_no_features,

    'yes_rate': [
        (df_train[col] == 'yes').mean()
        for col in yes_no_features
    ],

    'no_rate': [
        (df_train[col] == 'no').mean()
        for col in yes_no_features
    ],

    'median_price_yes': [
        df_train.loc[
            df_train[col] == 'yes',
            'price_doc'
        ].median()
        for col in yes_no_features
    ],

    'median_price_no': [
        df_train.loc[
            df_train[col] == 'no',
            'price_doc'
        ].median()
        for col in yes_no_features
    ]
})

summary_df

,feature,yes_rate,no_rate,median_price_yes,median_price_no
0,culture_objects_top_25,0.058204,0.941796,7300000.0,6100000.0
1,thermal_power_plant_raion,0.054195,0.945805,6500000.0,6100000.0
2,incineration_raion,0.082806,0.917194,5600000.0,6200000.0
3,oil_chemistry_raion,0.009864,0.990136,5670000.0,6150000.0
4,radiation_raion,0.359049,0.640951,6500000.0,5903808.0
5,railroad_terminal_raion,0.035213,0.964787,6551000.0,6114900.0
6,big_market_raion,0.091806,0.908194,5481000.0,6200000.0
7,nuclear_reactor_raion,0.028689,0.971311,6600000.0,6100000.0
8,detention_facility_raion,0.099902,0.900098,6570474.0,6100000.0
9,water_1line,0.078287,0.921713,5633610.0,6200000.0
10,big_road1_1line,0.026253,0.973747,7100000.0,6100000.0
11,railroad_1line,0.029200,0.970800,5415070.0,6150000.0
12,time_block,0.000000,0.000000,NaN,NaN

In [177]:
plot_df = summary_df.melt(
    id_vars='feature',
    value_vars=[
        'median_price_yes',
        'median_price_no'
    ],
    var_name='category',
    value_name='median_price'
)

fig = px.bar(
    plot_df,
    x='feature',
    y='median_price',
    color='category',
    barmode='group'
)

fig.update_layout(
    title='Как бинарные признаки влияют на цену?',
    xaxis_title="",
    yaxis_title="Цена"
)
fig.show()

По большинству бинарных признаков наблюдается умеренное различие медианной цены между категориями `yes` и `no`. Для части признаков наличие объекта или инфраструктуры (`culture_objects_top_25`, `big_road1_1line`, `nuclear_reactor_raion`) связано с более высокой медианной ценой, тогда как близость к промышленным или шумным объектам (`incineration_raion`, `railroad_1line`, `water_1line`) чаще соответствует более низкой стоимости жилья. Однако различия в целом не являются критически большими, поэтому данные признаки, вероятно, оказывают влияние на цену в комбинации с другими факторами, такими как локация, площадь и уровень урбанизации.

### Анализ макроэкономических данных

Также для решения задачи возьмем макроэкономические показатели за тот же период, и посмотрим какие из них влияют на ценообразование недвижимости

In [194]:
macro_df = pd.read_csv('../data/EDA_data/macro_EDA')
macro_df.head(5)

,Unnamed: 0,timestamp,oil_urals,gdp_quart,gdp_quart_growth,cpi,ppi,gdp_deflator,balance_trade,balance_trade_growth,...,provision_retail_space_modern_sqm,turnover_catering_per_cap,theaters_viewers_per_1000_cap,seats_theather_rfmin_per_100000_cap,museum_visitis_per_100_cap,bandwidth_sports,population_reg_sports_share,students_reg_sports_share,apartment_build,apartment_fund_sqm
0,0,2011-08-20,109.31,14313.7,3.3,354.0,420.7,86.721,15.459,10.1,...,271.0,6943.0,565.0,0.45356,1240.0,269768.0,22.37,64.12,23587.0,230310.0
1,1,2011-08-23,109.31,14313.7,3.3,354.0,420.7,86.721,15.459,10.1,...,271.0,6943.0,565.0,0.45356,1240.0,269768.0,22.37,64.12,23587.0,230310.0
2,2,2011-08-27,109.31,14313.7,3.3,354.0,420.7,86.721,15.459,10.1,...,271.0,6943.0,565.0,0.45356,1240.0,269768.0,22.37,64.12,23587.0,230310.0
3,3,2011-09-01,111.29,14313.7,3.3,353.2,434.4,86.721,15.386,10.1,...,271.0,6943.0,565.0,0.45356,1240.0,269768.0,22.37,64.12,23587.0,230310.0
4,4,2011-09-05,111.29,14313.7,3.3,353.2,434.4,86.721,15.386,10.1,...,271.0,6943.0,565.0,0.45356,1240.0,269768.0,22.37,64.12,23587.0,230310.0

In [195]:
print(min(macro_df['timestamp']), max(macro_df['timestamp']))

2011-08-20 2014-11-27

In [196]:
macro_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25445 entries, 0 to 25444
Columns: 101 entries, Unnamed: 0 to apartment_fund_sqm
dtypes: float64(94), int64(3), object(4)
memory usage: 19.6+ MB

In [197]:
print(macro_df.duplicated().sum())

0

In [200]:
numeric_columns = macro_df.select_dtypes(include=[np.number]).columns.tolist()

zero_negative_summary = []

for col in numeric_columns:
    zero_count = (macro_df[col] == 0).sum()
    neg_count = (macro_df[col] < 0).sum()

    zero_negative_summary.append({
        "column": col,
        "zero_count": zero_count,
        "zero_share": zero_count / len(macro_df),
        "negative_count": neg_count,
        "negative_share": neg_count / len(macro_df),
        "min": macro_df[col].min(),
        "median": macro_df[col].median(),
        "max": macro_df[col].max()
    })

zero_negative_summary = pd.DataFrame(zero_negative_summary).sort_values("zero_count", ascending=False)
zero_negative_summary

,column,zero_count,zero_share,negative_count,negative_share,min,median,max
0,Unnamed: 0,1,0.000039,0,0.0,0.0000,12722.000,25444.00
1,oil_urals,0,0.000000,0,0.0,78.9665,107.843,122.52
2,gdp_quart,0,0.000000,0,0.0,14313.7000,17442.100,20406.90
3,gdp_quart_growth,0,0.000000,0,0.0,0.6000,1.300,5.20
4,cpi,0,0.000000,0,0.0,353.0000,403.900,434.90
...,...,...,...,...,...,...,...,...
92,bandwidth_sports,0,0.000000,0,0.0,269768.0000,329348.000,398451.00
93,population_reg_sports_share,0,0.000000,0,0.0,22.3700,26.700,28.20
94,students_reg_sports_share,0,0.000000,0,0.0,64.1200,76.200,76.20
95,apartment_build,0,0.000000,0,0.0,23587.0000,46080.000,46352.00
96,apartment_fund_sqm,0,0.000000,0,0.0,226047.3000,229294.800,232840.20

Кажется что макроэкономические данные не нуждаются в очистке и не имеют аномалий

In [202]:
skew_macro = macro_df.select_dtypes(include='number').skew().sort_values(ascending=False)
skew_macro.head(10)

heating_share                   5.552083
water_pipes_share               5.552083
baths_share                     5.552083
hot_water_share                 5.320169
sewerage_share                  5.215566
grp_growth                      2.615497
retail_trade_turnover_growth    1.954312
power_clinics                   1.907523
income_per_cap                  1.882795
usdrub                          1.669102
dtype: float64

Сильной ассиметрии нет

In [185]:
macro_na_sum = macro_df.isna().sum().reset_index().rename(columns={0:'NA_sum', 'index':'feature'}).sort_values('NA_sum', ascending=False).head(30)
fig = px.bar(x=macro_na_sum['NA_sum'], y=macro_na_sum['feature'], title='Количество пропусков по признакам, топ 30')
fig.update_layout(
    xaxis_title="Кол во пропусков",
    yaxis_title="Числовые признаки"
)
fig.show()

Посмотрим на категориальные признаки

In [186]:
cat_macro = macro_df.select_dtypes(include='object').columns
for i in cat_macro:
    print(macro_df[i].value_counts())

child_on_acc_pre_school
7,311     366
45,713    365
#!        365
3,013     365
16,765    365
Name: count, dtype: int64
modern_education_share
90,92      365
93,08      365
95,4918    365
Name: count, dtype: int64
old_education_build_share
23,14     365
25,47     365
8,2517    365
Name: count, dtype: int64

Изменим тип данных на этих признаках

In [187]:
macro_df.loc[macro_df['child_on_acc_pre_school'] == '#!', 'child_on_acc_pre_school'] = np.nan

In [188]:
cat_macro = macro_df.select_dtypes(include='object').columns
for i in cat_macro:
    macro_df[i] = macro_df[i].str.replace(',', '.').astype('float')

In [189]:
cat_macro = macro_df.select_dtypes(include='object').columns
cat_macro

Index([], dtype='object')

In [190]:
final_df = df_cleaned.merge(macro_df, on='timestamp', how='left')

In [191]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25438 entries, 0 to 25437
Columns: 391 entries, timestamp to apartment_fund_sqm
dtypes: datetime64[ns](1), float64(219), int64(155), object(16)
memory usage: 75.9+ MB

In [203]:
final_df.to_csv('../data/EDA_data/cleaned_EDA')